@startuml
[suinput]
[uinput]
[Lua]
[Any Joystick Device] --> [evdev]
[evdev] --> [libevdev]
package "WeJoy" {
    libevdev --> [Event Loop Thread]
    [Event Loop Thread] --> Lua
    [Lua handler] --> [suinput]
}
Lua --> [User Script]
[User Script] --> [Lua handler]
suinput --> [uinput]
[uinput] --> [Virtual Keyboard]
[uinput] --> [Virtual Joystick]


@enduml